name: Build and Publish to NuGet

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          ${{ env.DOTNET_VERSION }}
        dotnet-quality: 'preview'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Generate version number
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          # For tag pushes, use the tag as version (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          # For branch pushes, generate version based on commit count and short SHA
          COMMIT_COUNT=$(git rev-list --count HEAD)
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="0.1.$COMMIT_COUNT-beta+$SHORT_SHA"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"
    
    - name: Build project
      run: dotnet build --configuration Release --no-restore -p:Version=${{ steps.version.outputs.version }}
    
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      continue-on-error: true
    
    - name: Pack NuGet package
      run: dotnet pack --configuration Release --no-build --output ./artifacts -p:Version=${{ steps.version.outputs.version }}
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts/*.nupkg
        retention-days: 7

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download package artifacts
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          ${{ env.DOTNET_VERSION }}
        dotnet-quality: 'preview'
    
    - name: Publish to NuGet
      run: |
        dotnet nuget push ./artifacts/*.nupkg \
          --source ${{ env.NUGET_SOURCE_URL }} \
          --api-key ${{ secrets.CLICKUP_MCPSERVER_NUGET_API_KEY }} \
          --skip-duplicate
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1